#!/bin/sh

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

# If run with the "config"-parameter, give out information on how the
# graphs should look. 
 
if [ "$1" = "config" ]; then

	echo 'graph_title LaCrosse sensor reading'
	echo 'graph_args --base 1000'
	echo 'graph_vlabel temperature'
	# We want Cur/Min/Avg/Max unscaled (i.e. 0.42 load instead of 420 milliload)
	echo 'graph_scale no'
	# Graph category. Defaults to 'other'
	echo 'graph_category sensors'
	# The fields. "label" is used in the legend. "label" is the only required subfield. 
	echo 'temp.label temperature'
	# These two read the environment for warning values for the field
	# "load".  If "load_warning" or "warning" aren't set in the
	# environment, no warning levels are set.  Likewise for "load_critical"
	# and "critical".
	print_warning temp
	print_critical temp
	echo 'graph_info LaCrosse wireless sensor readings'
	echo 'temp.info 5 minute temeperature'
	echo "temp.colour 00DD00"
	exit 0
fi

# If not run with any parameters at all (or only unknown ones), do the
# real work - i.e. display the data. Almost always this will be
# "value" subfield for every data field.

echo -n "temp.value "
sensor_id=`/opt/lcr/lcr-client localhost 2200 | awk -F: '{print $4}'`

if [ "$sensor_id" = "E8" ] 
then
    /opt/lcr/lcr-client localhost 2200 | awk -F: '{print $5}'
else
    echo ""
fi
